import type { Metadata } from "next"
import "./globals.css"
import MountMessageList from "@/components/MountMessageList"
import NavBar from "@/components/NavBar"
import ThemeProvider from "@/components/ThemeProvider"
import localFont from "next/font/local"
import type React from "react"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
})

export const metadata: Metadata = {
  title: "TaroBlog",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="cupcake" className="theme-transition">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative overflow-x-hidden`}
      >
        <ThemeProvider>
          <NavBar />
          {children}
          <MountMessageList />
        </ThemeProvider>
      </body>
    </html>
  )
}
